project:
  type: website

execute:
  engine: jupyter
  freeze: auto

website:
  title: "Diggy Digs Data"
  favicon: assets\img\favicons\favicon.ico
  page-navigation: true
  site-url: https://diggydigsdata.github.io
  repo-url: https://github.com/diggydigsdata
  repo-actions: [source]
  google-analytics: "G-HNQKPVKC29"

  open-graph: true

  navbar:
    background: "#A7D5E8"
    logo: assets\img\brand.png
    align: center
    title: Diggy Digs Data
    collapse-below: lg

    right:
      - text: Datasets
        href: datasets/index.qmd
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/diggydigsdata
      - icon: envelope
        href: mailto:diggydigsdata@gmail.com
      - icon: linkedin
        href: https://www.linkedin.com/in/eoindignan1989/
  
  page-footer:
    left: "This page is built with [Quarto](https://quarto.org/)."
    background: "#A7D5E8"
    right:
    - text: "License"
      href: LICENSE

format:
  html:
    theme:
      light: [flatly, styles.scss]
      dark: [flatly, styles-dark.scss]
    toc: true
    highlight-style: a11y-dark
    code-copy: true
    code-overflow: wrap

editor: source



