name: diggydigsdata
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - matplotlib
  - numpy
  - pandas
  - pingouin
  - scipy
  - seaborn
  - ipykernel
  - jupyter
  - conda-forge::plotly
  - conda-forge::chardet
  - conda-forge::fastparquet
  - conda-forge::sqlalchemy
  - pymysql
  - tabulate
  - conda-forge::python-dotenv
